### ISSUE TITLE
dllexp_GetMaxDivision fails on AX370-Gaming K7 motherboard

### ISSUE THREAD

**Issue by tylerszabo** [tylerszabo/RGB-Fusion-Tool#31]
`dllexp_GetMaxDivision` returns `0xFFFFFFFF` when the tool is run for any setting on the AX370-Gaming K7 motherboard. Full exception is as follows for v0.9.1:

```
Error: System.Reflection.TargetInvocationException: Exception has been thrown by
 the target of an invocation. ---> GLedApiDotNet.Raw.GLedAPIv1_0_0Exception: dll
exp_GetMaxDivision returned 0xFFFFFFFF
   at GLedApiDotNet.Raw.GLedAPIv1_0_0Wrapper.GetMaxDivision()
   at GLedApiDotNet.RGBFusionMotherboard..ctor(GLedAPIv1_0_0Wrapper wrapperAPI)
   at GLedApiDotNet.RGBFusionMotherboard..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOn
ly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Bo
olean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipChec
kThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean s
kipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at RGBFusionTool.RGBFusionMain.LazyMotherboard.get_Layout()
   at RGBFusionTool.Application.Main(String[] args)
```

Initially reported on a [Reddit thread](https://www.reddit.com/r/gigabytegaming/comments/8u11ug/aorus_app_center_riddled_with_bugs/e2bw87z/).

Similar to issue #30

**Comment by Chrispynutt** [comment]
Hi Joined GitHub, happy to check anything you want to test.

**Comment by Chrispynutt** [comment]
Okay tried:
`[MBId_101]
;; Test 1
LFType_1=1,1

;; Test 2
LFType_2=1,1

;; Test 3
LFType_3=1,1

;; Test 4
LFType_4=1,1

;; Test 5
LFType_5=1,1`
did a --list with no joy

**Comment by tylerszabo** [comment]
Curses. I've pinged Gigabyte with a similar issue but it'd probably help if you reached out on your own behalf as well. If they're [listing your board ](https://www.gigabyte.com/mb/rgb/) as RGB Fusion compatible on the page that lists the SDK the I'm hoping they'll patch it. It certainly seems like they're advertising it.

**Comment by Chrispynutt** [comment]
Looking at it I am not seeing entries in layout.ini for all of the Z270/H270/B250. Little support for X370/B350. It might be that the earliest form of RGB Fusion is just not compatible with the SDK. I will drop a line to Gigabyte.

**Comment by Chrispynutt** [comment]
Ticket raised

**Comment by tylerszabo** [comment]
One thing to keep in mind is that some of these boards *may* match the same MBId/LFType as an existing entry and just lack a comment that explains it's compatible. So I'm not sure I'd be ready to claim it doesn't support those boards without having someone test it.

**Comment by Chrispynutt** [comment]
Oh I agree you can see quite a few aren't listed on both sides, might be that they were rebranded at the last moment or a group of boards all share the same basic layout. Anyway lets see if my support ticket does anything.

**Comment by windows2000bug** [comment]
Looks like this is the same issue someone mentioned to me that they were having with their MB. IIRC I think he had a x470 Gaming 7. I just recall the Lazy error, which seems unique, compared to the other ones I have seen. Seeing all these different chipsets, and various boards for each socket, I wish they would really consolidate and/or standardize. Even if Gigabyte standardized the RGB zoning, it would be nice.

**Comment by windows2000bug** [comment]
You have done great work on this, I wish we would get more support from Gigabyte. If they really want an Aorus community, then they will need foster innovators.

**Comment by Chrispynutt** [comment]
Reply from Gigabyte:

> Hello, Our team has confirmed this board doesn't support for RGB Fusion SDK. 

:-/

**Comment by tylerszabo** [comment]
This is unfortunate :( thanks for following up.

In hopes that this issue is one day fixed I'm going to keep this issue open. If they has open sourced part of their RGB Fusion GUI I'd be able to add support directly. It's too bad because it'd sell their hardware better, too.

**Comment by daleriechert** [comment]
Confirming the same issue on an GA-AB350N-Gaming WIFI motherboard. First I learned that they have removed advertised features from the RGB Fusion software with the recent updates, now I'm learning that the SDK doesn't support my motherboard either. It's pathetic that an Arduino would be the preferred solution at this point.
