### ISSUE TITLE
dllexp_GetMaxDivision fails on Z270X-Gaming K5

### ISSUE THREAD

**Issue by Thurrax** [tylerszabo/RGB-Fusion-Tool#34]
# Bug Report

## Summary

Downloaded the latest archive and latest sdk from gigabyte. Extracted the DLLs and .INI file to the programs folder. Tried to run, but with an error.

### Steps and Commands

- Open CMD
- CD into Program Directory
- RGBFusionTool.exe --list or any cmdline will output that error

### Actual behavior

- Program does nothing, just outputs the error message

```
Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> GLedApiDotNet.Raw.GLedAPIv1_0_0Exception: dllexp_GetMaxDivision returned 0xFFFFFFFF
   at GLedApiDotNet.Raw.GLedAPIv1_0_0Wrapper.GetMaxDivision()
   at GLedApiDotNet.RGBFusionMotherboard..ctor(GLedAPIv1_0_0Wrapper wrapperAPI)
   at GLedApiDotNet.RGBFusionMotherboard..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at RGBFusionTool.RGBFusionMain.LazyMotherboard.get_Layout()
   at RGBFusionTool.Application.Main(String[] args)
```
## Environment
```
- Windows Version: 10.0.17134.0
- RGB Fusion Tool Version: 0.9.2
- Motherboard: Z270X-Gaming K5
- BIOS: F9c

Hashes:

D39AB2041C3A93ECB38CE446BBBC1C3DA1E3292EC25A301E4ADF3A588EE7A8F3 GLedApi.dll
A32CD85D5087290CD259902E7BF5F7559EFD4C2FD98A50B6BFFD9B98ACF86C27 GLedApiDotNet.dll
702A91752CE59B11078AB8F3428ECD1F871267D8AD45E414173CCF0A69FEE9D4 layout.ini
05FC657EB5B5D563DE7807DF6EE07FC8B89DC6F6F08EB76C30E5192429FBBDCF Mono.Options.dll
39CE6E142BBDDDE1FBA2BDFD5CC4030014E979E82B843D8762E2912E1207E2FB RGBFusionTool.exe
64BF4B2F0C84333E239DDA24F82BF8EAD22B7DB905C50FADE262283CA96703AD ycc.dll
```

**Comment by tylerszabo** [comment]
Curses, another one :( . I'm really surprised about this one I thought the Z270 boards would be more likely to work. Unfortunately they aren't listed in `layout.ini` so I'm not surprised that it's not supported (I'm starting to consider adding more information to that exception because this happens a lot as you can likely see from the other issues).

Please open a support request with Gigabyte; I really want them to fix this so that people with boards that say they support "RGB Fusion" can also use the SDK.

**Comment by Thurrax** [comment]
Opened a Ticket with GB. Hoping for the best.

**Comment by Thurrax** [comment]
Update: Gigabyte Support Answered. They told me that the 2XX Series Chipset is not supported by the SDK and it wont be fixed/patched or anything like that. Sad.
