### ISSUE TITLE
any luck using this with Aero 15x?

### ISSUE THREAD

**Issue by plj5003** [tylerszabo/RGB-Fusion-Tool#38]
Looking to give CLI based RGB instructions to various components.  No idea if it meets the Motherboard or Keyobard criteria.

**Comment by tylerszabo** [comment]
I suspect they may be under the peripherals; this might work after peripheral support is added (#37 )

**Comment by plj5003** [comment]
Thanks for getting back to me, I'll try it tonight!

**Comment by plj5003** [comment]
getting an error:

`Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at GLedApiDotNet.Raw.GLedAPIv1_0_0Impl.dllexp_InitAPI()
   at GLedApiDotNet.Raw.GLedAPIv1_0_0Impl.InitAPI()
   at GLedApiDotNet.Raw.GLedAPIv1_0_0Wrapper.Initialize()
   at GLedApiDotNet.RGBFusionMotherboard..ctor(GLedAPIv1_0_0Wrapper wrapperAPI)
   at GLedApiDotNet.RGBFusionMotherboard..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at RGBFusionTool.RGBFusionMain.LazyMotherboard.SetAll(LedSetting ledSetting)
   at RGBFusionTool.Application.Main(String[] args)`

**Comment by plj5003** [comment]
ran with admin prompt

**Comment by tylerszabo** [comment]
Ah; right - even if you have only peripherals `--list` will try to initialize the motherboard and fail if it's not working. I've made a minor change to list peripherals first in 116a61f. It'll still throw (I'm trying to think of how I want to handle the exceptions - I don't want to get too far away from wrapping the API; I definitely need to refactor now).

**Comment by plj5003** [comment]
Gotcha, it looks like the sdk was kind of half baked to begin with from the research I've done, so the fact you made it this far are makes you a saint lol.  I only know my way around data pipelines and python but if there is anyway I can aid your struggle let me know!

**Comment by tylerszabo** [comment]
I've attached a build of just the binaries for `116a61f` in case you don't have an easy local build environment. I didn't go to the work of packaging the dependencies in this one; I'm still working on making an easy CI build pipeline.

[RGBFusionTool_master_116a61f0b44b55435636eee4a24347caeb726067_22.zip](https://github.com/tylerszabo/RGB-Fusion-Tool/files/2555204/RGBFusionTool_master_116a61f0b44b55435636eee4a24347caeb726067_22.zip)

**Comment by plj5003** [comment]
Error: System.DllNotFoundException: Unable to load DLL 'GvLedLib.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at GvLedLibDotNet.Raw.GvLedLibv1_0Impl.dllexp_GvLedInitial(Int32& iDeviceCount, Int32[] iDeviceIdArray)
   at GvLedLibDotNet.Raw.GvLedLibv1_0Impl.GvLedInitial(Int32& iDeviceCount, Int32[] iDeviceIdArray) in D:\a\1\s\GvLedLibDotNet\Raw\GvLedLibv1_0Impl.cs:line 17
   at GvLedLibDotNet.Raw.GvLedLibv1_0Wrapper.Initialize() in D:\a\1\s\GvLedLibDotNet\Raw\GvLedLibv1_0Wrapper.cs:line 42
   at GvLedLibDotNet.RGBFusionPeripherals.<.ctor>b__3_0() in D:\a\1\s\GvLedLibDotNet\RGBFusionPeripherals.cs:line 75
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GvLedLibDotNet.RGBFusionPeripherals.get_Devices() in D:\a\1\s\GvLedLibDotNet\RGBFusionPeripherals.cs:line 84
   at RGBFusionTool.Application.Main(String[] args) in D:\a\1\s\RGBFusionTool\Application.cs:line 220
PS C:\Users\plj50\Downloads\RGBFusionTool_master_116a61f0b44b55435636eee4a24347caeb726067_22\RGBFusionTool_master_116a61

**Comment by tylerszabo** [comment]
I didn't include the dependencies in that zip; could you use the dependencies from the previous release?
