### ISSUE TITLE
Error: System.DllNotFoundException: Unable to load DLL 'GvLedLib.dll'

### ISSUE THREAD

**Issue by ThunderRoid** [tylerszabo/RGB-Fusion-Tool#40]
MB
Z370 Gaming 7

CMD
`RGBFusionTool.exe --list`

Error
```
C:\Users\Denocyte\Downloads\RGBFusionTool_v0.9.3>RGBFusionTool.exe --list
Zone 0: A_LED
Zone 1: A_LED
Zone 2: A_LED
Zone 3: A_LED
Zone 4: A_LED
Zone 5: NA
Zone 6: NA
Zone 7: D_LED_TYPE_2
Zone 8: D_LED_TYPE_2
Usage: RGBFusionTool.exe [OPTION]... [[LEDSETTING] | [ZONE LEDSETTING]...] [
peripherals GVSETTING]
Set RGB Fusion motherboard LEDs

Options:
  -v, --verbose
.
.
.

Error: System.DllNotFoundException: Unable to load DLL 'GvLedLib.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at GvLedLibDotNet.Raw.GvLedLibv1_0Impl.dllexp_GvLedInitial(Int32& iDeviceCount, Int32[] iDeviceIdArray)
   at GvLedLibDotNet.Raw.GvLedLibv1_0Impl.GvLedInitial(Int32& iDeviceCount, Int32[] iDeviceIdArray)
   at GvLedLibDotNet.Raw.GvLedLibv1_0Wrapper.Initialize()
   at GvLedLibDotNet.RGBFusionPeripherals.<.ctor>b__3_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GvLedLibDotNet.RGBFusionPeripherals.get_Devices()
   at RGBFusionTool.Application.Main(String[] args)
```

Files
![image](https://user-images.githubusercontent.com/3328263/49004116-6d4be680-f118-11e8-8d11-09dbc28c73dc.png)

**Comment by tylerszabo** [comment]
What are the hashes of the files?

Powershell:

```powershell
    @("GLedApi.dll", "GLedApiDotNet.dll", "layout.ini", "Mono.Options.dll", "RGBFusionTool.exe", "ycc.dll", "GvLedLib.dll", "GvLedLibDotNet.dll", "GvDisplay.dll", "GvBiosLib.dll") | % { Get-FileHash -Algorithm SHA256 -Path $_ }
```

In addition if you could look at use the [Dependencies](https://github.com/lucasg/Dependencies) tool on GvLedLib.dll that can show if there's a missing DLL (and then I can look about packaging it).

**Comment by ThunderRoid** [comment]
![image](https://user-images.githubusercontent.com/3328263/49065983-84e8a500-f1d4-11e8-841c-bc6554d263bb.png)

**Comment by tylerszabo** [comment]
Okay, those are all the right files. in that case could you definitely use [Dependencies ](https://github.com/lucasg/Dependencies) on `GVLedLib.dll` to find out what's missing.

**Comment by ThunderRoid** [comment]
Already installed 😕
![image](https://user-images.githubusercontent.com/3328263/49279314-03934b80-f43c-11e8-8fee-44a443b48f73.png)

**Comment by tylerszabo** [comment]
In that case could you use [Dependencies](https://github.com/lucasg/Dependencies) to tell me what you're missing?

**Comment by WheatTail** [comment]
Hi. I have the same issue. I've used Dependencies and figured out that it's mfc110ud.dll and MSVCR110D.dll are missing. Google says that vcredist 2012 contains it BUT i've installed both (x86 and x64) and the didn't appear. I've tryed to download dll directly and put it into RGBFusion folder but it didn't work.
![default](https://user-images.githubusercontent.com/34488873/50540637-92fc5d80-0ba6-11e9-8c14-1d403463df21.png)

**Comment by WheatTail** [comment]
Okay, mfc110d now checked as exist but msvcr110d still not. I've deleted vcredist 2012, installed it again, downloaded this dll manually - no success.
![default](https://user-images.githubusercontent.com/34488873/50540830-081d6200-0baa-11e9-9063-35dc51940ea4.png)

**Comment by WheatTail** [comment]
Soo strange. Dependencies still say "MSVCR110D.dll is missing", but
PS C:\Users\Amon\Desktop\rgbft> .\RGBFusionTool.exe --list
Zone 0: A_LED
Zone 1: A_LED
Zone 2: A_LED
Zone 3: A_LED
Zone 4: A_LED
Zone 5: NA
Zone 6: NA
Zone 7: D_LED_TYPE_2
Zone 8: D_LED_TYPE_2
Peripheral 0: Mouse_Pad_AORUS_P7
Peripheral 1: 20481
PS C:\Users\Amon\Desktop\rgbft>
--list works propely (almost). 20481 - is AORUS M5 mouse.

**Comment by BenLiyanage** [comment]
The 20481 is your ram. Same on my box.

**Comment by BenLiyanage** [comment]
I am having this same problem when trying to compile and build the source code.  There are no missing dependencies when I load the `GvLedLib.dll` into the dependency viewer that you referenced.  Any tips on building this project?

**Comment by tylerszabo** [comment]
@BenLiyanage perhaps GLedApi.dll? The .NET DLLs depend on .NET 4.6.

**Comment by tylerszabo** [comment]
@WheatTail I saw some additional IDs in the example files that weren't in the documentation so it might be related to those. Setting the LEDs there will need more work - peripheral support is a bit awkward. I'm debating pulling it out of the main releases and extending that in a separate branch because of the problems it's causing (especially with dependencies). I've reached out to Gigabyte to ask if they can package with the missing dependencies but they went silent.

**Comment by WheatTail** [comment]
@BenLiyanage , uh? But my ram is just Crucial Ballistix Elite, not an AORUS RGB ram, it haven't LEDs at all.

@tylerszabo , i've forked your project and add my M5 correct recognizing, also add color cycle mode for peripheral using your ColorCycleGvLedSetting.cs file by adding parser for it and it's work as in official RGB Fusion. Now trying to add pulse mode but it works... Weird. Ignoring color settings. I need to work on it.
I also submit a ticket in support and they're silent too.
SDK guide is just a crap.

**Comment by BenLiyanage** [comment]
The `DLL`'s do not show up in the `bin/debug` folder.  If I copy them there manually it also does not work.  When I use the pre-compiled distribution everything works fine.

**Comment by BenLiyanage** [comment]
@WheatTail my ram is a corsair model.  It's possible that `0x5001` is a grab bag for ram.

**Comment by BenLiyanage** [comment]
@tylerszabo Visual Studio says I have 4.7 installed.  That should be sufficient correct?

**Comment by BenLiyanage** [comment]
I have figured out my issue--I needed to copy these two DLLs into the build directory also:

* GvDisplay.dll
* GvBiosLib.dll

Are these supposed to be compiled into the project some how?  Where do they come from if they are not coming from the SDK?

**Comment by tylerszabo** [comment]
@BenLiyanage I had to pull them from other releases because the officially packaged ones were missing dependencies. Glad you got the compile working. Dependencies are certainly an issue with this project. I think it's probably time I prioritize issue #25. 

@WheatTail - cool, if you get it working and write some test coverage for it please submit a PR :)

**Comment by WheatTail** [comment]
@BenLiyanage , okay, probably RGB Fusion detects RAM all time have it LEDs or not. GvDistplay.dll and GvBios.dll you can get by installing latest official RGB Fusion BUT you also need GvIllumLib.dll, don't forget it

@tylerszabo , color cycle works pretty nice at this time but strange dependece from speed parameter. Than more speed - than slower P7 colors change and faster (till some point, 11 i guess) M5, and vice versa: than lower speed - than faster P7 LEDs color change and slower M5. But i have the same issue with official RGB Fusion. Probably it depends from M5 firmware. 
Without documentation it's a bit complicated. I've submit another ticket to Gigabyte techsupport and they say that this 35 crappy guide is all they have.  I don't believe them... But it can explain why their own RGB Fusion tool so bad.

**Comment by Emu1981** [comment]
I am having the same issues with the "Unable to load DLL 'GvLedLib.dll".  The issue appears to be that Gigabyte links the GvLedLib.dll file against debug versions of the DLLs which are not installed with the standard redistributible packages.  
The RGBFusion app from Gigabyte actually installs the relevant files into SysWOW64 and it looks like it is installing them alongside the Visual C++ 2008 redistributible.  I have attached a zip containing the two files that were installed with the RGBFusion app.  They are digitally signed by Microsoft and anyone who downloads them should double check to make sure that the signature is still intact.

[RGBFusion VC debug DLLs.zip](https://github.com/tylerszabo/RGB-Fusion-Tool/files/2826230/RGBFusion.VC.debug.DLLs.zip)


.

**Comment by tylerszabo** [comment]
Fantastic find! @Emu1981. That `d` is sneaky. Thanks also for checking the signatures. I'll bundle them in future releases. I'll keep this open until such a bundle is released and confirmed to work.

**Comment by ericnewton76** [comment]
Wow this is really awesome... you kinda stole my thunder because I had some grand schemes when I found gigabyte's sdk.  

Did you find a way to package the dependencies effectively?  The project might warrant a full installshield installation and a more robust dependency check.  

You might also run into gigabyte complaining about redistribution, but that can be solved by dependency checker including a link to a page on this repo which can then get you to the "right" sdk dlls to download.

I'm going to look into this more sometime this weekend and see if I can help out.

Btw, see if github.com/commandline/commandlineparser works for command line parsing.  I admin that project and noticed you were doing your own parsing and tests for parsing.

**Comment by Emu1981** [comment]
Well, I did some more digging and it turns out that, technically, Gigabyte is breaching the software license for Visual Studio by distributing the debug versions of the DLLs.  Gigabyte needs to sort out their build environment so that the DLLs are not linked and they need to fix their app so that they are not distributing the files without the license to do so.  I sent them a message regarding this but I have not gotten a response to it yet.

**Comment by h0useRus** [comment]
I've got new SDK B19.0311.1, but faced with same issue, and @Emu1981 doesn't work for me :(
